version: "3.9"

services:
  db:
    container_name: mongoDB
    image: mongo:latest
    restart: always
    volumes:
      - ./ticketworldData:/data/db
    environment:
      - MONGO_INITDB_DATABASE= ticketworld
    ports:
      - 27017:27017